name: fvf_flutter
version: 0.0.1+20
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  encrypt: ^5.0.3
  logger: ^2.6.1
  dio: ^5.9.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  flutter_staggered_animations: ^1.1.1
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.2.1
  permission_handler: ^12.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  auto_size_text: ^3.0.0
  gradient_borders: ^1.0.2
  share_plus: ^12.0.0
  supabase_flutter: ^2.10.2
  flutter_branch_sdk: ^8.9.0+1
  lottie: ^3.3.2
  socket_io_client: ^3.1.2
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  smart_auth: ^3.2.0
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  firebase_core: ^4.1.1
  animated_digit: ^3.3.2
  purchases_flutter: ^9.7.0
  zo_animated_border: ^1.0.3
  sleek_circular_slider: ^2.1.0
  gif: ^2.3.0
  image: ^4.5.4
  in_app_review: ^2.0.11
  no_screenshot: ^0.3.1
  emoji_regex: ^0.0.5

dev_dependencies:
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  fluttertoast: ^9.0.0
  platform: ^3.1.6
  collection: ^1.19.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/gif/
    - assets/locales/
    - assets/fonts/open_runde/
    - assets/lottie/

  fonts:
    - family: OpenRunde
      fonts:
        - asset: assets/fonts/open_runde/OpenRunde-Regular.otf
          weight: 400
        - asset: assets/fonts/open_runde/OpenRunde-Medium.otf
          weight: 500
        - asset: assets/fonts/open_runde/OpenRunde-Semibold.otf
          weight: 600
        - asset: assets/fonts/open_runde/OpenRunde-Bold.otf
          weight: 700
