name: fvf_flutter
version: 0.0.1+11
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  encrypt: ^5.0.3
  logger: ^2.6.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  flutter_staggered_animations: ^1.1.1
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  permission_handler: ^12.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  auto_size_text: ^3.0.0
  gradient_borders: ^1.0.1
  share_plus: ^11.1.0
  supabase_flutter: ^2.9.1
  flutter_branch_sdk: ^8.4.1
  lottie: ^3.3.1
  socket_io_client: ^3.1.2
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  image_picker: ^1.2.0
  smart_auth: ^3.2.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  firebase_core: ^4.0.0
  animated_digit: ^3.3.1+2
  purchases_flutter: ^9.2.3
  zo_animated_border: ^1.0.1
  sleek_circular_slider: ^2.1.0
  gif: ^2.3.0
  image: ^4.5.4
  in_app_review: ^2.0.11

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  flutter_test:
    sdk: flutter

dependency_overrides:
  fluttertoast: ^8.2.12
  platform: ^3.1.6
  collection: ^1.19.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/gif/
    - assets/locales/
    - assets/fonts/open_runde/
    - assets/lottie/

  fonts:
    - family: OpenRunde
      fonts:
        - asset: assets/fonts/open_runde/OpenRunde-Regular.otf
          weight: 400
        - asset: assets/fonts/open_runde/OpenRunde-Medium.otf
          weight: 500
        - asset: assets/fonts/open_runde/OpenRunde-Semibold.otf
          weight: 600
        - asset: assets/fonts/open_runde/OpenRunde-Bold.otf
          weight: 700
