/// Model representing country information including country code and flag emoji.
class CountryInfo {
  /// Constructor for creating a CountryInfo instance.
  const CountryInfo({
    required this.countryCode,
    required this.flagEmoji,
  });

  /// Country code (e.g., 'US', 'IN').
  final String countryCode;

  /// Flag emoji representing the country (e.g., '🇺🇸', '🇮🇳').
  final String flagEmoji;
}

/// Sample phone code → country map
const Map<String, CountryInfo> phoneCodeToCountry = <String, CountryInfo>{
  '1': CountryInfo(countryCode: 'US', flagEmoji: '🇺🇸'),
  '20': CountryInfo(countryCode: 'EG', flagEmoji: '🇪🇬'),
  '27': CountryInfo(countryCode: 'ZA', flagEmoji: '🇿🇦'),
  '30': CountryInfo(countryCode: 'GR', flagEmoji: '🇬🇷'),
  '31': CountryInfo(countryCode: 'NL', flagEmoji: '🇳🇱'),
  '32': CountryInfo(countryCode: 'BE', flagEmoji: '🇧🇪'),
  '33': CountryInfo(countryCode: 'FR', flagEmoji: '🇫🇷'),
  '34': CountryInfo(countryCode: 'ES', flagEmoji: '🇪🇸'),
  '36': CountryInfo(countryCode: 'HU', flagEmoji: '🇭🇺'),
  '39': CountryInfo(countryCode: 'IT', flagEmoji: '🇮🇹'),
  '40': CountryInfo(countryCode: 'RO', flagEmoji: '🇷🇴'),
  '41': CountryInfo(countryCode: 'CH', flagEmoji: '🇨🇭'),
  '42': CountryInfo(countryCode: 'CZ', flagEmoji: '🇨🇿'),
  '43': CountryInfo(countryCode: 'AT', flagEmoji: '🇦🇹'),
  '44': CountryInfo(countryCode: 'GB', flagEmoji: '🇬🇧'),
  '45': CountryInfo(countryCode: 'DK', flagEmoji: '🇩🇰'),
  '46': CountryInfo(countryCode: 'SE', flagEmoji: '🇸🇪'),
  '47': CountryInfo(countryCode: 'NO', flagEmoji: '🇳🇴'),
  '48': CountryInfo(countryCode: 'PL', flagEmoji: '🇵🇱'),
  '49': CountryInfo(countryCode: 'DE', flagEmoji: '🇩🇪'),
  '51': CountryInfo(countryCode: 'PE', flagEmoji: '🇵🇪'),
  '52': CountryInfo(countryCode: 'MX', flagEmoji: '🇲🇽'),
  '53': CountryInfo(countryCode: 'CU', flagEmoji: '🇨🇺'),
  '54': CountryInfo(countryCode: 'AR', flagEmoji: '🇦🇷'),
  '55': CountryInfo(countryCode: 'BR', flagEmoji: '🇧🇷'),
  '56': CountryInfo(countryCode: 'CL', flagEmoji: '🇨🇱'),
  '57': CountryInfo(countryCode: 'CO', flagEmoji: '🇨🇴'),
  '58': CountryInfo(countryCode: 'VE', flagEmoji: '🇻🇪'),
  '60': CountryInfo(countryCode: 'MY', flagEmoji: '🇲🇾'),
  '61': CountryInfo(countryCode: 'AU', flagEmoji: '🇦🇺'),
  '62': CountryInfo(countryCode: 'ID', flagEmoji: '🇮🇩'),
  '63': CountryInfo(countryCode: 'PH', flagEmoji: '🇵🇭'),
  '64': CountryInfo(countryCode: 'NZ', flagEmoji: '🇳🇿'),
  '65': CountryInfo(countryCode: 'SG', flagEmoji: '🇸🇬'),
  '66': CountryInfo(countryCode: 'TH', flagEmoji: '🇹🇭'),
  '81': CountryInfo(countryCode: 'JP', flagEmoji: '🇯🇵'),
  '82': CountryInfo(countryCode: 'KR', flagEmoji: '🇰🇷'),
  '84': CountryInfo(countryCode: 'VN', flagEmoji: '🇻🇳'),
  '86': CountryInfo(countryCode: 'CN', flagEmoji: '🇨🇳'),
  '90': CountryInfo(countryCode: 'TR', flagEmoji: '🇹🇷'),
  '91': CountryInfo(countryCode: 'IN', flagEmoji: '🇮🇳'),
  '92': CountryInfo(countryCode: 'PK', flagEmoji: '🇵🇰'),
  '93': CountryInfo(countryCode: 'AF', flagEmoji: '🇦🇫'),
  '94': CountryInfo(countryCode: 'LK', flagEmoji: '🇱🇰'),
  '95': CountryInfo(countryCode: 'MM', flagEmoji: '🇲🇲'),
  '98': CountryInfo(countryCode: 'IR', flagEmoji: '🇮🇷'),
  '212': CountryInfo(countryCode: 'MA', flagEmoji: '🇲🇦'),
  '213': CountryInfo(countryCode: 'DZ', flagEmoji: '🇩🇿'),
  '216': CountryInfo(countryCode: 'TN', flagEmoji: '🇹🇳'),
  '218': CountryInfo(countryCode: 'LY', flagEmoji: '🇱🇾'),
  '220': CountryInfo(countryCode: 'GM', flagEmoji: '🇬🇲'),
  '221': CountryInfo(countryCode: 'SN', flagEmoji: '🇸🇳'),
  '222': CountryInfo(countryCode: 'MR', flagEmoji: '🇲🇷'),
  '223': CountryInfo(countryCode: 'ML', flagEmoji: '🇲🇱'),
  '224': CountryInfo(countryCode: 'GN', flagEmoji: '🇬🇳'),
  '225': CountryInfo(countryCode: 'CI', flagEmoji: '🇨🇮'),
  '226': CountryInfo(countryCode: 'BF', flagEmoji: '🇧🇫'),
  '227': CountryInfo(countryCode: 'NE', flagEmoji: '🇳🇪'),
  '228': CountryInfo(countryCode: 'TG', flagEmoji: '🇹🇬'),
  '229': CountryInfo(countryCode: 'BJ', flagEmoji: '🇧🇯'),
  '230': CountryInfo(countryCode: 'MU', flagEmoji: '🇲🇺'),
  '231': CountryInfo(countryCode: 'LR', flagEmoji: '🇱🇷'),
  '232': CountryInfo(countryCode: 'SL', flagEmoji: '🇸🇱'),
  '233': CountryInfo(countryCode: 'GH', flagEmoji: '🇬🇭'),
  '234': CountryInfo(countryCode: 'NG', flagEmoji: '🇳🇬'),
  '235': CountryInfo(countryCode: 'TD', flagEmoji: '🇹🇩'),
  '236': CountryInfo(countryCode: 'CF', flagEmoji: '🇨🇫'),
  '237': CountryInfo(countryCode: 'CM', flagEmoji: '🇨🇲'),
  '238': CountryInfo(countryCode: 'CV', flagEmoji: '🇨🇻'),
  '239': CountryInfo(countryCode: 'ST', flagEmoji: '🇸🇹'),
  '240': CountryInfo(countryCode: 'GQ', flagEmoji: '🇬🇶'),
  '241': CountryInfo(countryCode: 'GA', flagEmoji: '🇬🇦'),
  '242': CountryInfo(countryCode: 'CG', flagEmoji: '🇨🇬'),
  '243': CountryInfo(countryCode: 'CD', flagEmoji: '🇨🇩'),
  '244': CountryInfo(countryCode: 'AO', flagEmoji: '🇦🇴'),
  '245': CountryInfo(countryCode: 'GW', flagEmoji: '🇬🇼'),
  '246': CountryInfo(countryCode: 'IO', flagEmoji: '🇮🇴'),
  '247': CountryInfo(countryCode: 'AC', flagEmoji: '🇦🇨'),
  '248': CountryInfo(countryCode: 'SC', flagEmoji: '🇸🇨'),
  '249': CountryInfo(countryCode: 'SD', flagEmoji: '🇸🇩'),
  '250': CountryInfo(countryCode: 'RW', flagEmoji: '🇷🇼'),
  '251': CountryInfo(countryCode: 'ET', flagEmoji: '🇪🇹'),
  '252': CountryInfo(countryCode: 'SO', flagEmoji: '🇸🇴'),
  '253': CountryInfo(countryCode: 'DJ', flagEmoji: '🇩🇯'),
  '254': CountryInfo(countryCode: 'KE', flagEmoji: '🇰🇪'),
  '255': CountryInfo(countryCode: 'TZ', flagEmoji: '🇹🇿'),
  '256': CountryInfo(countryCode: 'UG', flagEmoji: '🇺🇬'),
  '257': CountryInfo(countryCode: 'BI', flagEmoji: '🇧🇮'),
  '258': CountryInfo(countryCode: 'MZ', flagEmoji: '🇲🇿'),
  '260': CountryInfo(countryCode: 'ZM', flagEmoji: '🇿🇲'),
  '261': CountryInfo(countryCode: 'ZW', flagEmoji: '🇿🇼'),
  '262': CountryInfo(countryCode: 'RE', flagEmoji: '🇷🇪'),
  '263': CountryInfo(countryCode: 'ZW', flagEmoji: '🇿🇼'),
  '264': CountryInfo(countryCode: 'NA', flagEmoji: '🇳🇦'),
  '265': CountryInfo(countryCode: 'MW', flagEmoji: '🇲🇼'),
  '266': CountryInfo(countryCode: 'LS', flagEmoji: '🇱🇸'),
  '267': CountryInfo(countryCode: 'BW', flagEmoji: '🇧🇼'),
  '268': CountryInfo(countryCode: 'SZ', flagEmoji: '🇸🇿'),
  '269': CountryInfo(countryCode: 'KM', flagEmoji: '🇰🇲'),
  '290': CountryInfo(countryCode: 'SH', flagEmoji: '🇸🇭'),
  '291': CountryInfo(countryCode: 'ER', flagEmoji: '🇪🇷'),
  '292': CountryInfo(countryCode: 'ET', flagEmoji: '🇪🇹'),
  '293': CountryInfo(countryCode: 'DJ', flagEmoji: '🇩🇯'),
  '294': CountryInfo(countryCode: 'KE', flagEmoji: '🇰🇪'),
  '295': CountryInfo(countryCode: 'TZ', flagEmoji: '🇹🇿'),
};

/// Returns the CountryInfo for a given phone code.
/// Falls back to US 🇺🇸 if the phone code is not found.
CountryInfo getCountryInfoFromPhoneCode(String phoneCode) {
  phoneCode.replaceAll('+', '');
  return phoneCodeToCountry[phoneCode] ??
      const CountryInfo(
        countryCode: 'US',
        flagEmoji: '🇺🇸',
      );
}
